export const formInicial = {
  nombre: '',
  mesTerminacion: '',
  obra: 'MICROBACHEO',
  ubicacion: '',
  barrio: '',
  estado: 'Finalizada',
  fuente: 'Carga manual',
  inspector: '',
  realizo: '',
  cuadras: '',
  metrosLineales: '',
  metrosCuadrados: '',
  descripcion: '',
  direccion: '',
  latitud: '',
  longitud: '',
  geometriaTipo: 'Punto',
  geometria: [],
}
